import {
  isRouteErrorResponse,
  json,
  Links,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
  useRouteError,
} from '@remix-run/react';
import { LoaderFunctionArgs } from '@remix-run/node';
import Main from './components/main';
import { getSpacecrafts } from './shared/api/services/apiServices';
import Provider from './features/providers';

import './styles/index.scss';
import Wrapper from './components/layout/Wrapper';
import NotFoundPage from './components/notFoundPage';

export default function App() {
  return (
    <html lang="en">
      <head>
        <title>Star Trek</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create remix" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/favicon.png" />
        <Meta />
        <Links />
      </head>
      <body>
        <Provider>
          <Wrapper>
            <Main>
              <Outlet />
            </Main>
          </Wrapper>
        </Provider>
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export async function loader({ request }: LoaderFunctionArgs) {
  const url = new URL(request.url);
  const spacecraftsRes = await getSpacecrafts(url.searchParams);
  if (!spacecraftsRes) {
    throw new Response('Spacecrafts not found', { status: 404 });
  }
  return json({ spacecraftsRes });
}

export function ErrorBoundary() {
  const error = useRouteError();
  return (
    <html lang="en">
      <head>
        <title>Oops!</title>
        <Meta />
        <Links />
      </head>
      <body>
        {isRouteErrorResponse(error) && <NotFoundPage />}
        <Scripts />
      </body>
    </html>
  );
}
