import { ReactElement } from 'react';
import { GetServerSideProps } from 'next/types';
import Head from 'next/head';

import Layout from '@/components/layout/Layout';
import Main from '@/components/main';
import { SpacecraftsResponse } from '@/entities/spacecraft/models';
import { getSpacecrafts } from '@/shared/api/services';

interface Props {
  spacecraftsRes: SpacecraftsResponse
}

export const getServerSideProps: GetServerSideProps = (async (context) => {
  const spacecraftsRes = await getSpacecrafts(context)

  return { props: { spacecraftsRes } }
})

export default function Home({ spacecraftsRes }: Props) {
  return (
    <>
      <Head>
        <title>Star Trek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <main>
        <Main spacecraftsRes={spacecraftsRes}/>
      </main>
    </>
  );
}


Home.getLayout = (page: ReactElement) => {
  return <Layout>{page}</Layout>;
};
