import Main from '@/components/main';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Star Trek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <main>
        <Main />
      </main>
    </>
  );
}
