import { Metadata } from 'next';

import '@/styles/index.scss';

export const metadata: Metadata = {
  title: 'Star Trek',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
