import { Metadata } from 'next';
import Header from '@/components/header';

import '@/styles/index.scss';
import Providers from './providers';
import Wrapper from './_wrapper';

export const metadata: Metadata = {
  title: 'Star Trek',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Wrapper>{children}</Wrapper>
        </Providers>
      </body>
    </html>
  );
}
